### ISSUE TITLE
FacebookActivity missing

### ISSUE THREAD

**Issue by chrysophylaxdives** [chrysophylaxdives/pvt#1]
> FATAL EXCEPTION: main
                                                                            Process: org.caudimordax.grupp7.sdapp, PID: 6915
                                                                            Log in attempt failed: FacebookActivity could not be started. Please make sure you added FacebookActivity to the AndroidManifest.
                                                                                at com.facebook.login.LoginManager.startLogin(LoginManager.java:441)
                                                                                at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:299)
                                                                                at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:285)
                                                                                at com.facebook.login.widget.LoginButton$LoginClickListener.performLogin(LoginButton.java:734)
                                                                                at com.facebook.login.widget.LoginButton$LoginClickListener.onClick(LoginButton.java:701)
                                                                                at com.facebook.FacebookButtonBase$1.onClick(FacebookButtonBase.java:385)
                                                                                at android.view.View.performClick(View.java:5198)
                                                                                at android.view.View$PerformClick.run(View.java:21147)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by chrysophylaxdives** [comment]
![image](https://cloud.githubusercontent.com/assets/10576351/15164201/8b3ff97a-170d-11e6-8eda-678ee5290c8b.png)

Seems to be working
